name: Build Zip File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        path: 'main'

    - name: Checkout ${{ matrix.browser }} branch for manifest.json
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.browser }}
        path: ${{ matrix.browser }}

    - name: Prepare extension directory
      run: |
        mkdir extension
        cp -r main/icons main/scripts extension/
        cp ${{ matrix.browser }}/manifest.json extension/

    - name: Zip extension
      run: |
        zip -r ${{ matrix.browser }}.zip extension

    - name: Move zip file to main directory
      run: |
        mv ${{ matrix.browser }}.zip main/

    - name: Commit and Push
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions[bot]
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Build ${{ matrix.browser }} extension'
        add: 'main/*.zip'
        default_author: github_actions
        cwd: 'main'
      if: github.ref == 'refs/heads/main'
