name: Build Zip File

on:
  push:
    branches:
      - main 
      - chrome
      - firefox
    paths-ignore:
      - *.zip

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        path: 'workspace'
        token: ${{ secrets.PA_TOKEN }}
        
    - name: Checkout ${{ matrix.browser }} branch for manifest.json
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.browser }}
        path: ${{ matrix.browser }}
        token: ${{ secrets.PA_TOKEN }}

    - name: Prepare extension directory
      run: |
        mkdir extension
        cp -r workspace/icons workspace/scripts extension/
        cp ${{ matrix.browser }}/manifest.json extension/

    - name: Zip extension
      run: |
        zip -r ${{ matrix.browser }}.zip extension/icons extension/scripts extension/manifest.json

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update ${{ matrix.browser }}.zip" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PA_TOKEN }}
        branch: ${{ matrix.browser }}
