name: Build Zip File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        path: 'workspace'

    - name: Checkout ${{ matrix.browser }} branch for manifest.json
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.browser }}
        path: ${{ matrix.browser }}

    - name: Prepare extension directory
      run: |
        mkdir extension
        cp -r workspace/icons workspace/scripts extension/
        cp ${{ matrix.browser }}/manifest.json extension/

    - name: Zip extension
      run: |
        zip -r ${{ matrix.browser }}.zip extension

    - name: Move zip file to a separate directory
      run: |
        mkdir -p workspace/zipped-extensions
        mv ${{ matrix.browser }}.zip workspace/zipped-extensions/

    - name: Commit and Push
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add zipped-extensions/*
        git commit -m 'Build ${{ matrix.browser }} extension'
        git push origin main
      env:
        PA_TOKEN: ${{ secrets.PA_TOKEN }}
      if: github.ref == 'refs/heads/main'
